import type { CodegenOptions } from './types.js';

/**
 * Deterministic project scaffolding. Never model-generated: config, fixtures
 * and env plumbing must be identical across runs so only spec files vary.
 * Env variables appear by NAME only; values are injected at runtime.
 */
export function buildScaffold(
  options: CodegenOptions,
  meta: { sourceJobId: string; codegenJobId: string; generatedAt: string },
): Record<string, string> {
  const envNames = [...new Set(['BASE_URL', ...options.envVars])];

  const header = `// Generated by testcase-forge codegen
// source test-generation job: ${meta.sourceJobId}
// codegen job: ${meta.codegenJobId}
// generated at: ${meta.generatedAt}
`;

  const envTs = `${header}
/** Central env access. Values come from the runtime environment, never code. */
export function requireEnv(name: string): string {
  const value = process.env[name];
  if (value === undefined || value === '') {
    throw new Error(\`Missing required environment variable: \${name}\`);
  }
  return value;
}

export const env = {
${envNames.map((n) => `  ${n}: process.env.${n} ?? ''`).join(',\n')}
};
`;

  const config = `${header}
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 4 : undefined,
  reporter: [
    ['list'],
    ['html', { open: 'never' }],
    ['json', { outputFile: 'results/results.json' }],
  ],
  use: {
    baseURL: process.env.BASE_URL ?? ${JSON.stringify(options.baseUrl)},
    trace: 'on',
    video: 'on',
    screenshot: 'only-on-failure',
  },
  projects: [
    { name: 'setup', testMatch: /auth\\.setup\\.ts/ },
    {
      name: 'chromium',
      // Default state = anonymous but locale-forced, so even no-auth specs render
      // in the configured UI language. Authenticated specs override via test.use().
      use: { ...devices['Desktop Chrome'], storageState: 'results/.auth/anon.json' },
      dependencies: ['setup'],
    },
  ],
});
`;

  const authSetup = `${header}
import { mkdirSync, copyFileSync, writeFileSync } from 'node:fs';
import { test as setup, expect } from '@playwright/test';
import { requireEnv } from './support/env.js';

/**
 * Generic credential login: locale-independent selectors (input types), storage
 * state saved once and reused for every persona key referenced by the specs.
 * Credentials come exclusively from the runtime environment.
 *
 * UI language: TEST_LOCALE (default ${JSON.stringify(options.uiLocale)}) is written to
 * localStorage BEFORE app hydration, because this SPA hard-defaults to another
 * language and only honours the stored value. The forced locale is captured into
 * every saved storage state, and an anonymous state carries it to no-auth specs.
 */
setup('authenticate personas', async ({ page, baseURL }) => {
  setup.setTimeout(150_000);
  mkdirSync('results/.auth', { recursive: true });

  const authPath = process.env.AUTH_PATH ?? '/auth';
  const locale = process.env.TEST_LOCALE ?? ${JSON.stringify(options.uiLocale)};
  const localeKey = process.env.TEST_LOCALE_KEY ?? ${JSON.stringify(options.localeStorageKey)};
  const email = requireEnv('TEST_USER_EMAIL');
  const password = requireEnv('TEST_USER_PASSWORD');
  const onAuthRoute = new RegExp(authPath.replace(/\\//g, '\\\\/'));

  // Runs before any page script on every navigation in this context.
  await page.addInitScript(
    ([key, value]) => {
      try { window.localStorage.setItem(key, value); } catch { /* ignore */ }
    },
    [localeKey, locale] as const,
  );

  // Write the anonymous storage state (locale only, no session) for no-auth specs.
  const origin = new URL(baseURL ?? process.env.BASE_URL ?? 'http://localhost').origin;
  writeFileSync(
    'results/.auth/anon.json',
    JSON.stringify({
      cookies: [],
      origins: [{ origin, localStorage: [{ name: localeKey, value: locale }] }],
    }),
  );

  // SPA-safe login: wait out hydration, verify the filled values actually stick
  // (hydration can wipe inputs), and never click before the app is interactive —
  // otherwise the click triggers a native form submit that reloads the page.
  const attemptLogin = async () => {
    await page.goto(authPath);
    await page.waitForLoadState('networkidle').catch(() => {});
    const emailInput = page.locator('input[type="email"]').first();
    const passwordInput = page.locator('input[type="password"]').first();
    await expect(emailInput).toBeVisible({ timeout: 20_000 });
    await expect(async () => {
      await emailInput.fill(email);
      await passwordInput.fill(password);
      expect(await emailInput.inputValue()).toBe(email);
      expect(await passwordInput.inputValue()).toBe(password);
    }).toPass({ timeout: 20_000 });
    await page.locator('button[type="submit"]').first().click();
  };

  await attemptLogin();
  try {
    await expect(page).not.toHaveURL(onAuthRoute, { timeout: 25_000 });
  } catch {
    // One retry covers the pre-hydration native-submit race on cold loads.
    await attemptLogin();
    await expect(page).not.toHaveURL(onAuthRoute, { timeout: 45_000 });
  }
  await page.waitForLoadState('networkidle').catch(() => {});

  const primary = 'results/.auth/user.json';
  await page.context().storageState({ path: primary });
  // Same account backs every persona key until per-persona credentials exist.
  for (const key of ['admin', 'default', 'authenticated']) {
    copyFileSync(primary, \`results/.auth/\${key}.json\`);
  }
});
`;

  const packageJson = `${JSON.stringify(
    {
      name: 'generated-playwright-suite',
      private: true,
      scripts: {
        test: 'playwright test',
        'test:headed': 'playwright test --headed',
        report: 'playwright show-report',
      },
      devDependencies: { '@playwright/test': '^1.49.0' },
    },
    null,
    2,
  )}\n`;

  const envExample = `# Runtime environment for the generated suite. Values are never committed.
${envNames.map((n) => `${n}=`).join('\n')}
`;

  const readme = `# Generated Playwright Suite

Generated by testcase-forge codegen job \`${meta.codegenJobId}\`
from test-generation job \`${meta.sourceJobId}\` at ${meta.generatedAt}.

## Run

\`\`\`bash
npm install && npx playwright install chromium
cp .env.example .env   # fill values
npx playwright test
\`\`\`

Videos, traces and screenshots land in \`test-results/\`; every test carries a
traceability header comment linking back to its test-case and coverage-item ids.
`;

  return {
    'package.json': packageJson,
    'playwright.config.ts': config,
    'tests/support/env.ts': envTs,
    'tests/auth.setup.ts': authSetup,
    '.env.example': envExample,
    'README.md': readme,
  };
}
